// tests/cpp-parser.test.ts
// TDD test suite for the UE C++ macro regex parser.
// Implementation target: src/parsers/cpp-parser.ts
//
// Strategy: Pure unit tests — no file I/O. All inputs are raw .h content strings.
// Tests cover UCLASS/UPROPERTY/UFUNCTION parsing, inheritance, includes, and edge cases.
// ≥25 tests covering all documented UE macro patterns.

import { parseCppFile } from '../src/parsers/cpp-parser.js';
import type { ParsedCppFile, UClassDecl, UPropertyDecl, UFunctionDecl } from '../src/parsers/cpp-parser.js';

// ---------------------------------------------------------------------------
// Shared test fixtures
// ---------------------------------------------------------------------------

/** A realistic AMyCharacter header with multiple macros and includes. */
const FULL_HEADER = `
// AMyCharacter.h — generated by UHT
#pragma once

#include "CoreMinimal.h"
#include "GameFramework/Character.h"
#include "MyCharacter.generated.h"

UCLASS(BlueprintType, Blueprintable)
class MYGAME_API AMyCharacter : public ACharacter
{
    GENERATED_BODY()

public:
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Stats")
    float Health;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Stats", meta=(ClampMin="0", ClampMax="100"))
    float Stamina;

    UPROPERTY(EditAnywhere, BlueprintReadOnly, Category="Combat")
    AActor* TargetActor;

    UFUNCTION(BlueprintCallable, Category="Combat")
    void Attack();

    UFUNCTION(Server, Reliable, WithValidation)
    void ServerFire(float Damage);
};
`.trim();

/** A plain header with no UE macros — only includes. */
const PLAIN_HEADER = `
#pragma once
#include "CoreMinimal.h"
#include <vector>

struct FMyPlainStruct {
    int X;
    int Y;
};
`.trim();

/** Multi-line UPROPERTY with complex meta block. */
const MULTILINE_UPROPERTY_HEADER = `
#pragma once
#include "CoreMinimal.h"
#include "MyActor.generated.h"

UCLASS()
class MYGAME_API AMyActor : public AActor
{
    GENERATED_BODY()

public:
    UPROPERTY(
        EditAnywhere,
        BlueprintReadWrite,
        Category="Stats",
        meta=(ClampMin="0", ClampMax="100", EditCondition="bEnabled")
    )
    float Health;
};
`.trim();

/** UCLASS with meta specifier. */
const UCLASS_WITH_META = `
#pragma once
#include "MyThing.generated.h"

UCLASS(meta=(ToolTip="My class description"))
class AMyThing : public UObject
{
    GENERATED_BODY()
};
`.trim();

/** UCLASS with no specifiers. */
const UCLASS_EMPTY_SPECIFIERS = `
#pragma once
#include "Empty.generated.h"

UCLASS()
class AEmpty : public UObject
{
    GENERATED_BODY()
};
`.trim();

/** Header with a TArray property. */
const TARRAY_HEADER = `
#pragma once
#include "CoreMinimal.h"
#include "HitResult.generated.h"

UCLASS()
class AHitTester : public AActor
{
    GENERATED_BODY()

public:
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Combat")
    TArray<FHitResult> HitResults;
};
`.trim();

/** Header with multiple inheritance (class and interface). */
const MULTIPLE_INHERITANCE_HEADER = `
#pragma once
#include "MyActor.generated.h"

UCLASS()
class AMultiInheritor : public AActor, public IMyInterface
{
    GENERATED_BODY()
};
`.trim();

/** Header with DECLARE_DYNAMIC_MULTICAST_DELEGATE — should be skipped. */
const DELEGATE_HEADER = `
#pragma once
#include "MyDelegate.generated.h"

DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam(FOnHealthChanged, float, NewHealth);

UCLASS()
class AWithDelegate : public AActor
{
    GENERATED_BODY()

public:
    UPROPERTY(BlueprintAssignable, Category="Events")
    FOnHealthChanged OnHealthChanged;
};
`.trim();

// ---------------------------------------------------------------------------
// parseCppFile — edge cases
// ---------------------------------------------------------------------------

describe('parseCppFile — edge cases', () => {
  it('returns success for empty string input', () => {
    const result = parseCppFile('');
    expect(result.success).toBe(true);
    if (result.success) {
      expect(result.data.classes).toHaveLength(0);
      expect(result.data.includes).toHaveLength(0);
      expect(result.data.rawContent).toBe('');
    }
  });

  it('returns success for plain header with no UE macros', () => {
    const result = parseCppFile(PLAIN_HEADER);
    expect(result.success).toBe(true);
    if (result.success) {
      expect(result.data.classes).toHaveLength(0);
    }
  });

  it('preserves rawContent verbatim in the result', () => {
    const content = '// just a comment\n#include "A.h"';
    const result = parseCppFile(content);
    expect(result.success).toBe(true);
    if (result.success) {
      expect(result.data.rawContent).toBe(content);
    }
  });

  it('never throws — even on wildly malformed input', () => {
    expect(() => parseCppFile('{{{{UCLASS((((')).not.toThrow();
    expect(() => parseCppFile('UPROPERTY(\n\n\n')).not.toThrow();
    expect(() => parseCppFile(null as unknown as string)).not.toThrow();
  });
});

// ---------------------------------------------------------------------------
// parseCppFile — #include extraction
// ---------------------------------------------------------------------------

describe('parseCppFile — #include extraction', () => {
  it('extracts a double-quoted #include path', () => {
    const result = parseCppFile('#include "CoreMinimal.h"');
    expect(result.success).toBe(true);
    if (result.success) {
      expect(result.data.includes).toContain('CoreMinimal.h');
    }
  });

  it('extracts an angle-bracket #include path', () => {
    const result = parseCppFile('#include <vector>');
    expect(result.success).toBe(true);
    if (result.success) {
      expect(result.data.includes).toContain('<vector>');
    }
  });

  it('extracts all #include directives from FULL_HEADER in order', () => {
    const result = parseCppFile(FULL_HEADER);
    expect(result.success).toBe(true);
    if (result.success) {
      expect(result.data.includes).toEqual([
        'CoreMinimal.h',
        'GameFramework/Character.h',
        'MyCharacter.generated.h',
      ]);
    }
  });

  it('extracts both quoted and angled includes from PLAIN_HEADER', () => {
    const result = parseCppFile(PLAIN_HEADER);
    expect(result.success).toBe(true);
    if (result.success) {
      expect(result.data.includes).toContain('CoreMinimal.h');
      expect(result.data.includes).toContain('<vector>');
    }
  });

  it('returns empty includes array when no #include directives present', () => {
    const result = parseCppFile('// no includes here\nclass Foo {};');
    expect(result.success).toBe(true);
    if (result.success) {
      expect(result.data.includes).toHaveLength(0);
    }
  });
});

// ---------------------------------------------------------------------------
// parseCppFile — UCLASS parsing
// ---------------------------------------------------------------------------

describe('parseCppFile — UCLASS parsing', () => {
  it('parses UCLASS with no specifiers — specifiers: [], meta: {}', () => {
    const result = parseCppFile(UCLASS_EMPTY_SPECIFIERS);
    expect(result.success).toBe(true);
    if (result.success) {
      expect(result.data.classes).toHaveLength(1);
      const cls = result.data.classes[0]!;
      expect(cls.specifiers).toEqual([]);
      expect(cls.meta).toEqual({});
    }
  });

  it('parses UCLASS specifiers: ["BlueprintType", "Blueprintable"]', () => {
    const result = parseCppFile(FULL_HEADER);
    expect(result.success).toBe(true);
    if (result.success) {
      const cls = result.data.classes[0]!;
      expect(cls.specifiers).toContain('BlueprintType');
      expect(cls.specifiers).toContain('Blueprintable');
    }
  });

  it('parses UCLASS class name correctly', () => {
    const result = parseCppFile(FULL_HEADER);
    expect(result.success).toBe(true);
    if (result.success) {
      expect(result.data.classes[0]!.name).toBe('AMyCharacter');
    }
  });

  it('parses inheritance — parentClass: "ACharacter"', () => {
    const result = parseCppFile(FULL_HEADER);
    expect(result.success).toBe(true);
    if (result.success) {
      expect(result.data.classes[0]!.parentClass).toBe('ACharacter');
    }
  });

  it('captures only the first public parent from multiple inheritance', () => {
    const result = parseCppFile(MULTIPLE_INHERITANCE_HEADER);
    expect(result.success).toBe(true);
    if (result.success) {
      expect(result.data.classes[0]!.parentClass).toBe('AActor');
    }
  });

  it('parses UCLASS meta specifier into meta record', () => {
    const result = parseCppFile(UCLASS_WITH_META);
    expect(result.success).toBe(true);
    if (result.success) {
      const cls = result.data.classes[0]!;
      expect(cls.meta).toMatchObject({ ToolTip: 'My class description' });
    }
  });

  it('captures the line number of the class declaration', () => {
    const result = parseCppFile(FULL_HEADER);
    expect(result.success).toBe(true);
    if (result.success) {
      // Line numbers are 1-based; the class line exists somewhere > 1
      expect(result.data.classes[0]!.line).toBeGreaterThan(1);
    }
  });
});

// ---------------------------------------------------------------------------
// parseCppFile — UPROPERTY parsing
// ---------------------------------------------------------------------------

describe('parseCppFile — UPROPERTY parsing', () => {
  it('parses UPROPERTY specifiers: ["EditAnywhere", "BlueprintReadWrite", ...]', () => {
    const result = parseCppFile(FULL_HEADER);
    expect(result.success).toBe(true);
    if (result.success) {
      const health = result.data.classes[0]!.properties.find((p) => p.name === 'Health')!;
      expect(health.specifiers).toContain('EditAnywhere');
      expect(health.specifiers).toContain('BlueprintReadWrite');
    }
  });

  it('parses UPROPERTY Category specifier verbatim including quotes', () => {
    const result = parseCppFile(FULL_HEADER);
    expect(result.success).toBe(true);
    if (result.success) {
      const health = result.data.classes[0]!.properties.find((p) => p.name === 'Health')!;
      expect(health.specifiers).toContain('Category="Stats"');
    }
  });

  it('parses UPROPERTY meta=(ClampMin, ClampMax) into meta record', () => {
    const result = parseCppFile(FULL_HEADER);
    expect(result.success).toBe(true);
    if (result.success) {
      const stamina = result.data.classes[0]!.properties.find((p) => p.name === 'Stamina')!;
      expect(stamina.meta).toMatchObject({ ClampMin: '0', ClampMax: '100' });
    }
  });

  it('parses plain property type: "float Health"', () => {
    const result = parseCppFile(FULL_HEADER);
    expect(result.success).toBe(true);
    if (result.success) {
      const health = result.data.classes[0]!.properties.find((p) => p.name === 'Health')!;
      expect(health.type).toBe('float');
      expect(health.name).toBe('Health');
    }
  });

  it('parses pointer property type: "AActor* TargetActor"', () => {
    const result = parseCppFile(FULL_HEADER);
    expect(result.success).toBe(true);
    if (result.success) {
      const target = result.data.classes[0]!.properties.find((p) => p.name === 'TargetActor')!;
      expect(target.type).toBe('AActor*');
      expect(target.name).toBe('TargetActor');
    }
  });

  it('parses TArray template property: "TArray<FHitResult> HitResults"', () => {
    const result = parseCppFile(TARRAY_HEADER);
    expect(result.success).toBe(true);
    if (result.success) {
      const prop = result.data.classes[0]!.properties.find((p) => p.name === 'HitResults')!;
      expect(prop.type).toBe('TArray<FHitResult>');
      expect(prop.name).toBe('HitResults');
    }
  });

  it('parses multi-line UPROPERTY with meta=(ClampMin, ClampMax, EditCondition)', () => {
    const result = parseCppFile(MULTILINE_UPROPERTY_HEADER);
    expect(result.success).toBe(true);
    if (result.success) {
      const cls = result.data.classes[0]!;
      const health = cls.properties.find((p) => p.name === 'Health')!;
      expect(health).toBeDefined();
      expect(health.specifiers).toContain('EditAnywhere');
      expect(health.specifiers).toContain('BlueprintReadWrite');
      expect(health.meta).toMatchObject({
        ClampMin: '0',
        ClampMax: '100',
        EditCondition: 'bEnabled',
      });
    }
  });

  it('records the 1-based line number of the UPROPERTY macro', () => {
    const result = parseCppFile(FULL_HEADER);
    expect(result.success).toBe(true);
    if (result.success) {
      const health = result.data.classes[0]!.properties.find((p) => p.name === 'Health')!;
      expect(health.line).toBeGreaterThan(0);
    }
  });
});

// ---------------------------------------------------------------------------
// parseCppFile — UFUNCTION parsing
// ---------------------------------------------------------------------------

describe('parseCppFile — UFUNCTION parsing', () => {
  it('parses UFUNCTION(BlueprintCallable, Category="Combat") specifiers', () => {
    const result = parseCppFile(FULL_HEADER);
    expect(result.success).toBe(true);
    if (result.success) {
      const attack = result.data.classes[0]!.functions.find((f) => f.name === 'Attack')!;
      expect(attack.specifiers).toContain('BlueprintCallable');
      expect(attack.specifiers).toContain('Category="Combat"');
    }
  });

  it('parses UFUNCTION(Server, Reliable, WithValidation) — all three specifiers', () => {
    const result = parseCppFile(FULL_HEADER);
    expect(result.success).toBe(true);
    if (result.success) {
      const serverFire = result.data.classes[0]!.functions.find((f) => f.name === 'ServerFire')!;
      expect(serverFire.specifiers).toContain('Server');
      expect(serverFire.specifiers).toContain('Reliable');
      expect(serverFire.specifiers).toContain('WithValidation');
    }
  });

  it('parses UFUNCTION return type "void" correctly', () => {
    const result = parseCppFile(FULL_HEADER);
    expect(result.success).toBe(true);
    if (result.success) {
      const attack = result.data.classes[0]!.functions.find((f) => f.name === 'Attack')!;
      expect(attack.returnType).toBe('void');
    }
  });

  it('parses UFUNCTION function name correctly', () => {
    const result = parseCppFile(FULL_HEADER);
    expect(result.success).toBe(true);
    if (result.success) {
      const names = result.data.classes[0]!.functions.map((f) => f.name);
      expect(names).toContain('Attack');
      expect(names).toContain('ServerFire');
    }
  });

  it('records the 1-based line number of the UFUNCTION macro', () => {
    const result = parseCppFile(FULL_HEADER);
    expect(result.success).toBe(true);
    if (result.success) {
      const attack = result.data.classes[0]!.functions.find((f) => f.name === 'Attack')!;
      expect(attack.line).toBeGreaterThan(0);
    }
  });
});

// ---------------------------------------------------------------------------
// parseCppFile — full integration
// ---------------------------------------------------------------------------

describe('parseCppFile — full integration', () => {
  it('parses FULL_HEADER: 1 class, 3 properties, 2 functions, 3 includes', () => {
    const result = parseCppFile(FULL_HEADER);
    expect(result.success).toBe(true);
    if (result.success) {
      expect(result.data.classes).toHaveLength(1);
      expect(result.data.classes[0]!.properties).toHaveLength(3);
      expect(result.data.classes[0]!.functions).toHaveLength(2);
      expect(result.data.includes).toHaveLength(3);
    }
  });

  it('DELEGATE_HEADER: DECLARE_DYNAMIC_MULTICAST_DELEGATE is skipped — 1 class with 1 property', () => {
    const result = parseCppFile(DELEGATE_HEADER);
    expect(result.success).toBe(true);
    if (result.success) {
      expect(result.data.classes).toHaveLength(1);
      expect(result.data.classes[0]!.properties).toHaveLength(1);
      expect(result.data.classes[0]!.functions).toHaveLength(0);
    }
  });

  it('parses all property names from FULL_HEADER in declaration order', () => {
    const result = parseCppFile(FULL_HEADER);
    expect(result.success).toBe(true);
    if (result.success) {
      const names = result.data.classes[0]!.properties.map((p) => p.name);
      expect(names).toEqual(['Health', 'Stamina', 'TargetActor']);
    }
  });

  it('parses all function names from FULL_HEADER in declaration order', () => {
    const result = parseCppFile(FULL_HEADER);
    expect(result.success).toBe(true);
    if (result.success) {
      const names = result.data.classes[0]!.functions.map((f) => f.name);
      expect(names).toEqual(['Attack', 'ServerFire']);
    }
  });

  it('Stamina UPROPERTY: specifiers exclude meta key, meta is a separate record', () => {
    const result = parseCppFile(FULL_HEADER);
    expect(result.success).toBe(true);
    if (result.success) {
      const stamina = result.data.classes[0]!.properties.find((p) => p.name === 'Stamina')!;
      // meta=(...) should NOT appear as a raw specifier string
      const hasRawMeta = stamina.specifiers.some((s) => s.startsWith('meta='));
      expect(hasRawMeta).toBe(false);
      // The meta record is populated instead
      expect(stamina.meta['ClampMin']).toBe('0');
    }
  });

  it('handles pathological multi-line collector — does not hang on 500+ line paren block', () => {
    // T-04-02 DoS mitigation: limit collector to 500 lines
    const manyLines = Array(600).fill('    SomeText,').join('\n');
    const pathological = `
#pragma once
UCLASS()
class AFoo : public AActor {
GENERATED_BODY()
public:
UPROPERTY(
${manyLines}
)
float X;
};`.trim();
    const result = parseCppFile(pathological);
    // Must not hang or throw — may succeed or fail gracefully
    expect(['success', 'object']).toContain(typeof result);
  });
});
