// JSON-newline framing types for communication with the UE C++ plugin.
// The UE plugin (Phase 7) runs a TCP server on PLUGIN_PORT that speaks this protocol:
//   - Each message is a JSON object followed by a newline character (\n)
//   - Client sends MCPCommand, server responds with MCPResponse
//   - correlationId is generated by the client, echoed by the server for matching

export interface MCPCommand {
  type: string;
  correlationId: string;
  payload?: unknown;
}

export interface MCPResponse {
  success: boolean;
  correlationId: string;
  data?: unknown;
  error?: string;
}
